"use client";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import { AuthProvider } from "./context/AuthContext";
import { useState } from "react";
import { ModalProvider } from "./context/ModalContext";
import { SnackbarProvider } from "./context/SnackBarContext";
const poppins = Poppins({ subsets: ["latin"], weight: ["600", "700", "400"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [burgerOpen, setBurgerOpen] = useState(false);
  return (
    <html lang="en" className={poppins.className}>
      <SnackbarProvider>
        <AuthProvider>
          <ModalProvider>
            <body
              className={`bg-blur min-h-screen h-full relative ${
                burgerOpen ? "overflow-hidden" : ""
              } `}
            >
              <Navigation
                burgerOpen={burgerOpen}
                setBurgerOpen={setBurgerOpen}
              />

              <div
                className={`w-full mx-auto container p-10 max-md:p-5 max-xl:p-8 overflow-x-hidden box-border ${
                  burgerOpen ? "opacity-20" : ""
                } `}
                onClick={() => {
                  setBurgerOpen(false);
                }}
              >
                {children}
              </div>
            </body>
          </ModalProvider>
        </AuthProvider>
      </SnackbarProvider>
    </html>
  );
}
